package com.android.andersenrickandmorty.common

object FiltersOnline {
    // I took it out separately as there are a lot of them
    val charactersStatusesOnline = sortedSetOf("Alive", "Dead", "unknown")
    val charactersSpeciesOnline = sortedSetOf(
        "Alien",
        "Animal",
        "Cronenberg",
        "Disease",
        "Human",
        "Humanoid",
        "Mythological Creature",
        "Poopybutthole",
        "Robot",
        "unknown"
    )
    val charactersGendersOnline = sortedSetOf("Female", "Genderless", "Male", "unknown")
    val charactersTypesOnline = sortedSetOf(
        "",
        "Alligator-Person",
        "Alphabetrian",
        "Amoeba-Person",
        "Animal",
        "Anime",
        "Artificial Intelligence",
        "Bepisian",
        "Bird-Person",
        "Bird-Person Human Mix",
        "Blue ape alien",
        "Boobie buyer reptilian",
        "Boobloosian",
        "Bread",
        "CHUD",
        "CHUD Human Mix",
        "Cat",
        "Cat controlled dead lady",
        "Cat-Person",
        "Caterpillar",
        "Centaur",
        "Chair",
        "Changeformer",
        "Clay-Person",
        "Clone",
        "Cone-nippled alien",
        "Conjoined twin",
        "Cookie",
        "Corn-person",
        "Cromulon",
        "Cronenberg",
        "Crow",
        "Crow Horse",
        "Cyborg",
        "Decoy",
        "Demon",
        "Dog",
        "Doopidoo",
        "Dragon",
        "Drumbloxian",
        "Dummy",
        "Eat shiter-Person",
        "Eel",
        "Elephant-Person",
        "Ferkusian",
        "Fish-Person",
        "Flansian",
        "Floop Floopian",
        "Fly",
        "Game",
        "Garblovian",
        "Gazorpian",
        "Gazorpian reproduction robot",
        "Gear-Person",
        "Genetic experiment",
        "Giant",
        "Giant Cat Monster",
        "Giant Incest Baby",
        "Glorzo",
        "God",
        "Goddess",
        "Gramuflackian",
        "Grandma",
        "Greebybobe",
        "Gromflomite",
        "Guinea Pig for the Polio Vaccine",
        "Hairy alien",
        "Half Soulless Puppet",
        "Hammerhead-Person",
        "Hivemind",
        "Hole",
        "Hologram",
        "Human Gazorpian",
        "Human with a flower in his head",
        "Human with antennae",
        "Human with ants in his eyes",
        "Human with baby legs",
        "Human with giant head",
        "Human with tusks",
        "Human-Snake hybrid",
        "Interdimensional gaseous being",
        "Jellybean",
        "Korblock",
        "Krootabulan",
        "Larva alien",
        "Leprechaun",
        "Light bulb-Alien",
        "Little Human",
        "Lizard",
        "Lizard-Person",
        "Lobster-Alien",
        "Mannie",
        "Mascot",
        "Meeseeks",
        "Mega Gargantuan",
        "Memory",
        "Mexican",
        "Microverse inhabitant",
        "Miniverse inhabitant",
        "Monogatron",
        "Monster",
        "Morglutzian",
        "Morty's toxic side",
        "Mytholog",
        "Nano Alien",
        "Narnian",
        "Necrophiliac",
        "Normal Size Bug",
        "Numbericon",
        "Octopus-Person",
        "Old Amazons",
        "Omniscient being",
        "Organic gun",
        "Parasite",
        "Phone",
        "Phone-Person",
        "Pickle",
        "Pizza",
        "Planet",
        "Plutonian",
        "Pripudlian",
        "Rat",
        "Rick's toxic side",
        "Ring-nippled alien",
        "Robot",
        "Robot-Crocodile hybrid",
        "Scarecrow",
        "Scrotian",
        "Self-aware arm",
        "Sentient ant colony",
        "Sexy Aquaman",
        "Shapeshifter",
        "Shimshamian",
        "Shrimp",
        "Slartivartian",
        "Slug",
        "Snail alien",
        "Snake",
        "Soulless Puppet",
        "Squid",
        "Stair goblin",
        "Starfish",
        "Summon",
        "Super Sperm Monster",
        "Superhuman",
        "Superhuman (Ghost trains summoner)",
        "Teddy Bear",
        "Teenyverse inhabitant",
        "Tentacle alien",
        "The Devil",
        "Tiger",
        "Time God",
        "Tinymouth",
        "Toy",
        "Traflorkian",
        "Trunk-Person",
        "Tumblorkian",
        "Turkey",
        "Turkey Human Mix",
        "Tuskfish",
        "Unknown-nippled alien",
        "Vampire",
        "Wasp",
        "Weasel",
        "Whenwolf",
        "Zeus",
        "Zigerion",
        "Zombodian"
    )
    val locationsTypesOnline = sortedSetOf(
        "Arcade",
        "Artificially generated world",
        "Box",
        "Cluster",
        "Convention",
        "Customs",
        "Daycare",
        "Diegesis",
        "Dimension",
        "Dream",
        "Dwarf planet (Celestial Dwarf)",
        "Fantasy town",
        "Game",
        "Liquid",
        "Machine",
        "Menagerie",
        "Microverse",
        "Miniverse",
        "Mount",
        "Nightmare",
        "Non-Diegetic Alternative Reality",
        "Planet",
        "Quadrant",
        "Quasar",
        "Resort",
        "Spa",
        "Space station",
        "Spacecraft",
        "TV",
        "Teenyverse",
        "Woods",
        "unknown"
    )
    val locationsDimensionsOnline = sortedSetOf(
        "Chair Dimension",
        "Cromulon Dimension",
        "Cronenberg Dimension",
        "Dimension 5-126",
        "Dimension C-137",
        "Dimension C-35",
        "Dimension C-500A",
        "Dimension D-99",
        "Dimension D716",
        "Dimension D716-B",
        "Dimension D716-C",
        "Dimension J-22",
        "Dimension J19ζ7",
        "Dimension K-22",
        "Dimension K-83",
        "Eric Stoltz Mask Dimension",
        "Evil Rick's Target Dimension",
        "Fantasy Dimension",
        "Fascist Dimension",
        "Fascist Shrimp Dimension",
        "Fascist Teddy Bear Dimension",
        "Giant Telepathic Spiders Dimension",
        "Magic Dimension",
        "Phone Dimension",
        "Pizza Dimension",
        "Post-Apocalyptic Dimension",
        "Replacement Dimension",
        "Testicle Monster Dimension",
        "Tusk Dimension",
        "Unknown dimension",
        "Wasp Dimension",
        "unknown"
    )
    val episodesEpisodesOnline = sortedSetOf(
        "S01E01",
        "S01E02",
        "S01E03",
        "S01E04",
        "S01E05",
        "S01E06",
        "S01E07",
        "S01E08",
        "S01E09",
        "S01E10",
        "S01E11",
        "S02E01",
        "S02E02",
        "S02E03",
        "S02E04",
        "S02E05",
        "S02E06",
        "S02E07",
        "S02E08",
        "S02E09",
        "S02E10",
        "S03E01",
        "S03E02",
        "S03E03",
        "S03E04",
        "S03E05",
        "S03E06",
        "S03E07",
        "S03E08",
        "S03E09",
        "S03E10",
        "S04E01",
        "S04E02",
        "S04E03",
        "S04E04",
        "S04E05",
        "S04E06",
        "S04E07",
        "S04E08",
        "S04E09"
    )
}